# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-17 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='url',
            new_name='bookmark_url',
        ),
    ]
