# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-17 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0002_auto_20200517_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
